
version: '3.8'

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: johan
            POSTGRES_PASSWORD: 26339777
            POSTGRES_DB: santuario
        ports:
            - "4040:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
